### ISSUE TITLE
TODO Frontend Days 2023

### ISSUE THREAD

**Issue by mvdam** [code-star/typescript-react-101#4]
- [x] Replace Michael with Corneel
- [x] Move Interval as bonus after exercise 7 (refactor earlier code to have less code)
- [x] Check where the solution code needs to live, stackblitz or in this repo? What about a preview of the end result? (Github pages?)
- [x] Exercise 4 rewrite to:

    1. Start button, setIsRunning(true)
    2. Use effect, listens to isRunning, setStartTime state or setElapsedTime when stopped
    3. Stop button -> setIsRunning(false)
